sudo: required
language: groovy
jdk:
  - openjdk8
  - oraclejdk9
services:
  - docker
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq -y install graphviz
  - sudo pip install awscli
install:
  - sudo apt-get install -y realpath
git:
  submodules: true
env:
  global:
  - GRADLE_OPTS='-Dorg.gradle.daemon=false'
before_script:
  - rm $HOME/.gitconfig
  - mkdir -p "$HOME/.nextflow" && echo "providers.github.auth='$NXF_GITHUB_ACCESS_TOKEN'" > "$HOME/.nextflow/scm"
script:
  - make assemble test install && export WITH_DOCKER='-with-docker' && ./integration-tests.sh
after_script:
  - bash pub-tests.sh travis
