sudo: required
language: groovy
jdk:
  - openjdk8
services:
  - docker
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq -y install graphviz
  - sudo pip install awscli
install:
  - sudo apt-get install -y realpath
git:
  submodules: true
env:
  matrix:
  - TEST_JDK=
  - TEST_JDK=9
  - TEST_JDK=10
  - TEST_JDK=11
  global:
  - GRADLE_OPTS='-Dorg.gradle.daemon=false'
before_script:
  - rm $HOME/.gitconfig
  - mkdir -p "$HOME/.nextflow" && echo "providers.github.auth='$NXF_GITHUB_ACCESS_TOKEN'" > "$HOME/.nextflow/scm"
  - make assemble
script:
  - |
    set -e;
    make test install;
    ./integration-tests.sh
after_script:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash pub-tests.sh travis; fi
